### ISSUE TITLE
npm run dev has erros

### ISSUE THREAD

**Issue by duanzonglong** [MacKentoch/react-redux-bootstrap-webpack-starter#1]
D:\developtool\nodework\react-redux-bootstrap-webpack-starter-master>npm run dev

> react-redux-bootstrap-webpack-starter@0.2.2 dev D:\developtool\nodework\react-redux-bootstrap-webpack-starter-master
> NODE_ENV=dev webpack

'NODE_ENV' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

npm ERR! Windows_NT 10.0.10240
npm ERR! argv "D:\\developtool\\tools\\nodejs\\node.exe" "D:\\developtool\\tools\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! code ELIFECYCLE
npm ERR! react-redux-bootstrap-webpack-starter@0.2.2 dev: `NODE_ENV=dev webpack`
npm ERR! Exit status 1

I has do
setx NODE_ENV=dev
or set NODE_ENV=dev

**Comment by MacKentoch** [comment]
Hi @duanzonglong,

Thank you for taking time submitting this issues.

I was sincerely not aware of this behaviors.
I only had experience with windows 7.
Windows is always full of surprises 😄 

I now change to `setx` for windows versions command.

**Comment by MacKentoch** [comment]
Now changed.
I keep this issue open 'till tomorrow so that I will have to see at work if it is ok on windows 7 (or if `set` would be better).

**Comment by duanzonglong** [comment]
Hi
I will try in mac again.





------------------ 原始邮件 ------------------
发件人: "Erwan DATIN";<notifications@github.com>;
发送时间: 2016年7月17日(星期天) 中午12:19
收件人: "MacKentoch/react-redux-bootstrap-webpack-starter"<react-redux-bootstrap-webpack-starter@noreply.github.com>; 
抄送: "青雨水烟"<339007811@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [MacKentoch/react-redux-bootstrap-webpack-starter] npm run devhas erros (#1)




Hi @duanzonglong,
 
Thank you for taking time submitting this issues.
 
I was sincerely not aware of this behaviors.
 I only had experience with windows 7.
 Windows is always full of surprises  
 
I now change to setx for windows versions command.

**Comment by MacKentoch** [comment]
To be honest I still did not have opportunity to test on windows.

On Mac OSX El Capitan it is no problem (in fact it is never a problem on Mac 😄 ).
