### ISSUE TITLE
Hot reload not working

### ISSUE THREAD

**Issue by seshvs** [MacKentoch/react-redux-bootstrap-webpack-starter#10]
Hi

I'm facing an issue. Hot reload is not working. not sure whats the issue.

Clone the project. yarn install then run 'yarn run start' .

I changed Home.js but nothing is reflected. webpack is restarted, however the changes are not reflected in the browser. Even i refresh nothing happens. 

operating system - Ubuntu

Any clue ... 

Thanks
Sesh

**Comment by MacKentoch** [comment]
Hi @seshvs 

I need a bit more information to be able to help you.

- What are your node js and yarn versions?
- What is your navigator name and version?
- do you have errors un the console that could give more details?

**Comment by MacKentoch** [comment]
This may be related to macOS import/export files can resolve even if filename cases are not respected.
In linux it does not work.

But as no more information I close this issue
