### ISSUE TITLE
16.0

### ISSUE THREAD

**Issue by MarcusXiaoFan** [MacKentoch/react-redux-bootstrap-webpack-starter#12]
When updated to react 16?

**Comment by MacKentoch** [comment]
I wait for all dependencies to be React 16 proof.

Update to 16 should be pretty straight forward.

**Comment by MacKentoch** [comment]
Time has come: this repo is the first one to upgrade to React 16.

**Comment by MacKentoch** [comment]
https://github.com/MacKentoch/react-redux-bootstrap-webpack-starter#breaking-changes-since-v500
