### ISSUE TITLE
SCRIPT5022: Minified React error #31 in IE11

### ISSUE THREAD

**Issue by D-kit** [MacKentoch/react-redux-bootstrap-webpack-starter#14]
npm run serve-prod
http://localhost:8082

Minified React error #31; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7B%24%24typeof%2C%20type%2C%20key%2C%20ref%2C%20props%2C%20_owner%7D&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

**Comment by MacKentoch** [comment]
Hi @D-kit 

That's a bit strange.

I've just tested again against: Firefox, Chrome, and Safari (all up to date versions): it is ok.
I don't have windows so I can't check IE11.

There is no reason why it would not work.

Try removing node_modules `rm -rf node_modules` then re-installs all `npm install`.
Ensure having NodeJS 8.x (6.x should be ok but just in case).

Then if still encountering the issue, then run `npm serve-dev` to get a more detailed error message.

**Comment by D-kit** [comment]
Hi @MacKentoch!

I have NodeJS 6.9.1. It is ok.
I resolve it issue.

**Comment by wSLecHayfIeNdock** [comment]
add babel-polyfill.
```
entry: {
        libs: ['babel-polyfill', 'react-redux', 'redux', 'immutable', 'redux-saga'],
        app: './index.js'
 },
```

**Comment by joeyrob** [comment]
> add babel-polyfill.
> 
> ```
> entry: {
>         libs: ['babel-polyfill', 'react-redux', 'redux', 'immutable', 'redux-saga'],
>         app: './index.js'
>  },
> ```

whete should i add this?
