### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by gaohuasheng** [MacKentoch/react-redux-bootstrap-webpack-starter#16]
206160 verbose stack Error: puppeteer@1.12.2 install: `node install.js`
206160 verbose stack Exit status 1
206160 verbose stack     at EventEmitter.<anonymous> (D:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:245:16)
206160 verbose stack     at emitTwo (events.js:106:13)
206160 verbose stack     at EventEmitter.emit (events.js:191:7)
206160 verbose stack     at ChildProcess.<anonymous> (D:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
206160 verbose stack     at emitTwo (events.js:106:13)
206160 verbose stack     at ChildProcess.emit (events.js:191:7)
206160 verbose stack     at maybeClose (internal/child_process.js:850:16)
206160 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
206161 verbose pkgid puppeteer@1.12.2
206162 verbose cwd D:\nodejsworkspace\reactspace\react-redux-bootstrap-webpack-starter
206163 error Windows_NT 6.1.7601
206164 error argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
206165 error node v6.2.0
206166 error npm  v3.8.9
206167 error code ELIFECYCLE
206168 error puppeteer@1.12.2 install: `node install.js`
206168 error Exit status 1
206169 error Failed at the puppeteer@1.12.2 install script 'node install.js'.
206169 error Make sure you have the latest version of node.js and npm installed.
206169 error If you do, this is most likely a problem with the puppeteer package,
206169 error not with npm itself.
206169 error Tell the author that this fails on your system:
206169 error     node install.js
206169 error You can get information on how to open an issue for this project with:
206169 error     npm bugs puppeteer
206169 error Or if that isn't available, you can get their info via:
206169 error     npm owner ls puppeteer
206169 error There is likely additional logging output above.
206170 verbose exit [ 1, true ]

**Comment by MacKentoch** [comment]
Hi @gaohuasheng ,

As far as I can see, it seems like you use node js v6 and you are on windows system.

I suggest:
- you use [nvm-windows](https://github.com/coreybutler/nvm-windows) **to manage multiple NodeJS versions**
- and you install `NodeJS 10` and use `v10` for `react-redux-bootstrap-webpack-starter` (*delete `node_modules` and reinstall with node js 10*)

Node JS 6 won't work anymore (NodeJS 8 is now the minimum required btw).

**Comment by gaohuasheng** [comment]
$ npm install
npm WARN acorn-dynamic-import@4.0.0 requires a peer of acorn@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap@4.3.1 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap@4.3.1 requires a peer of popper.js@^1.14.7 but none is installed. You must install peer dependencies yourself.
npm WARN react-addons-test-utils@15.6.2 requires a peer of react-dom@^15.4.2 but none is installed. You must install peer dependencies yourself.
npm WARN react-tap-event-plugin@3.0.3 requires a peer of react@^16.0.0-0 < 16.4.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-tap-event-plugin@3.0.3 requires a peer of react-dom@^16.0.0-0 < 16.4.0 but none is installed. You must install peer dependencies yourself.

audited 37210 packages in 42.17
found 69 vulnerabilities (66 low, 3 moderate)
  run `npm audit fix` to fix them, or `npm audit` for details

When I upgrade nodejs to 10.15,  run 

> npm install

 get  warnings upper . Then I run 

> npm run dev

 , I got this error below.

_ERROR in ./src/front/routes/routes.js 5:9
Module parse failed: Unexpected token (5:9)
You may need an appropriate loader to handle this file type.
|
| export var Home = loadable(function () {
>   return import('../pages/home');
| }, {
|   modules: ['../pages/home']
 @ ./src/front/Root.js 30:0-47 58:19-31
 @ ./src/front/index.js
Child html-webpack-plugin for "..\index.html":
     1 asset
    Entrypoint undefined = ../index.html
    [./node_modules/html-webpack-plugin/lib/loader.js!./src/front/statics/index.html] 953 bytes {0} [built]
    [./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 472 bytes {0} [built]
    [./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 497 bytes {0} [built]
        + 1 hidden module
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! react-redux-bootstrap-webpack-starter@6.1.0 dev: `cross-env NODE_ENV=dev webpack --config webpack.dev.config.js`_

I upgrade Nodejs by msi file latest.  Update npm by cammand 

> npm install -g npm

**Comment by selfsecurellc** [comment]
I'm getting the same errors as @gaohuasheng , is there a way to fix those?

**Comment by MacKentoch** [comment]
@selfsecurellc do you run windows or linux or macOS?

**Comment by selfsecurellc** [comment]
@MacKentoch MacOS

**Comment by selfsecurellc** [comment]
Worked, thanks!

**Comment by MacKentoch** [comment]
Sorry for that (time lost etc...).

I will investigate and fix it

**Comment by selfsecurellc** [comment]
@MacKentoch just out of curiosity, I'm working on a platform (I'm a backend developer) and need some help on the UI. I'd like to just focus on the backend architecture, do you do freelance work?

**Comment by MacKentoch** [comment]
@selfsecurellc my current company contract prevents me from working freelance on my free time...
Sad but legal in France.

**Comment by MacKentoch** [comment]
@selfsecurellc but message me at https://keybase.io/mackentoch if you need tips

**Comment by MacKentoch** [comment]
closing since no more feedback for a while.

Re-open whenever you fell in same issue
