### ISSUE TITLE
CSS Modules Enabled

### ISSUE THREAD

**Issue by JamesLeBoeuf** [MacKentoch/react-redux-bootstrap-webpack-starter#6]
Firstly, wanted to say thanks for the hard work you put in making this repo. It's exactly what I was looking for and got tired of finding starter templates that we're either way bloated or too simple. Also really nice to see the redux implementation as well. Great work!

This isn't really an issue it's a feature enhancement and maybe I'm just trying to incorporate it incorrectly but I'd like to have **css-modules** enabled. I've gone into the **webpack.dev.config.js** and added 
`modules: true` 
inside of the css and scss loaders, like so 
```
      {
        test: /\.css$/,
        use:  SPLIT_STYLE 
          ? ExtractTextPlugin.extract({
            fallback: 'style-loader',
            use: [
              {loader: 'css-loader', options: { importLoaders: 1, modules: true, localIdentName: '[hash:base64:5]' }},
              'postcss-loader'
            ]
          })
          : [
            'style-loader',
            {loader: 'css-loader', options: { importLoaders: 1, modules: true, localIdentName: '[hash:base64:5]' }},
            'postcss-loader'
          ]
      },
      {
        test: /\.scss$/,
        use:  SPLIT_STYLE 
        ? ExtractTextPlugin.extract({
          fallback: 'style-loader',
          use: [
            {loader: 'css-loader', options: { importLoaders: 1, modules: true, localIdentName: '[hash:base64:5]' }},
            'postcss-loader',
            'sass-loader'
          ]
        })
        : [
          'style-loader',
          {loader: 'css-loader', options: { importLoaders: 1, modules: true, localIdentName: '[hash:base64:5]' }},
          'postcss-loader',
          'sass-loader'
        ]
      },
```
Then I run npm start in terminal and it's not picking up an imported style, for instance
```import { base } from './home.scss';``` but when console.log it's giving `undefined`.

I then thought to go into the **webpack.hot.reload.config.js** file and add ```modules: true``` like so
```
      {
        test: /\.css$/,
        use:  [
          'style-loader',
          {loader: 'css-loader', options: { importLoaders: 1, modules: true, localIdentName: '[hash:base64:5]' }},
          'postcss-loader'
        ]
      },
      {
        test:  /\.scss$/,
        use:  [
          'style-loader',
          {loader: 'css-loader', options: { importLoaders: 1, modules: true, localIdentName: '[hash:base64:5]' }},
          'postcss-loader',
          'sass-loader'
        ]
      },
```
I go into console and log base and it's giving me what I'm looking for but the page is rendering pretty off. 
![screen shot 2017-06-08 at 10 09 47 am](https://user-images.githubusercontent.com/7974277/26906874-b8af6fc0-4c32-11e7-873b-8e7d31fac8a4.png)

**Comment by MacKentoch** [comment]
Hi @JamesLeBoeuf 

Thank you for your nice feedback!

I did not even have a try with css-loader.

But it is good enhancement.
I guess I would start with some example like [this one](https://github.com/RaphaelHadjadj/webpack2-cssmodules-sass/blob/master/webpack.config.js). 

I'm not sure it works but when I'm struggling with something new, I try to learn from others.

**Comment by MacKentoch** [comment]
Added CSSModule for sass styles (*Left css for vendors*).
